# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e464f8f74a3755e31c068802d7ff2d12220f0e9431a2fbbd65a256a403bb45b2ce9faab0315ff19bd2c24292979252329b0db8b3d553303203349a10ad95aa6

test:
  secret_key_base: c14478d2a8784446e9dffd231e93b39851526626cc28370b2abc05ea283984175f0386118e5e498be263c41d68cd0fb81813cff04fe3c3d50a641eb73cd8554c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
